import time
from colorama import *
init()
print("Bruh hacking tool by Matthew v1.2")
print("\n")


ip = input("Enter target IP adress: ")

print("Connecting to " + ip)
time.sleep(4)
print("Breaking throught firewall...")
time.sleep(2)
print("Firewall succesfully passed")
print("Initializing connection...")
time.sleep(1)
print("Connection succesfull")
print("Starting DDOS attack")

#DDOS (fake)

time.sleep(2)
print("")
print("Starting sending packages to " + ip)
print("Sending DDOS package 1")
time.sleep(1)
print(Fore.GREEN + "Succesful...")
print(Fore.WHITE + "Sending DDOS package 2")
time.sleep(1)
print(Fore.GREEN + "Succesful...")
print(Fore.WHITE + "Sending DDOS package 3")
time.sleep(1)
print(Fore.GREEN + "Succesful...")
print(Fore.WHITE + "Sending DDOS package 4")
time.sleep(1)
print(Fore.GREEN + "Succesful...")
print(Fore.WHITE + "Sending DDOS package 5")
time.sleep(1)
print(Fore.GREEN + "Succesful...")
time.sleep(1)
print(Fore.WHITE + "Sending DDOS package 6")
time.sleep(1)
print(Fore.GREEN + "Succesful...")
print(Fore.WHITE + "Sending DDOS package 7")
time.sleep(1)
print(Fore.GREEN + "Succesful...")
print(Fore.WHITE + "Sending DDOS package 8")
time.sleep(1)
print(Fore.GREEN + "Succesful...")
print(Fore.WHITE + "Sending DDOS package 9")
time.sleep(1)
print(Fore.GREEN + "Succesful...")
print(Fore.WHITE + "Sending DDOS package 10")
time.sleep(1)
print(Fore.GREEN + "Succesful...")
print(Fore.WHITE + "Sending DDOS package 11")
time.sleep(1)
print(Fore.GREEN + "Succesful...")
print(Fore.WHITE + "Sending DDOS package 12")
time.sleep(1)
print(Fore.GREEN + "Succesful...")
print(Fore.WHITE + "Sending DDOS package 13")
time.sleep(1)
print(Fore.GREEN + "Succesful...")
print(Fore.WHITE + "Sending DDOS package 14")
time.sleep(1)
print(Fore.GREEN + "Succesful...")
print(Fore.WHITE + "Sending DDOS package 15")
time.sleep(1)
print(Fore.GREEN + "Succesful...")
print(Fore.WHITE + "Attack succesfully finished...")
time.sleep(2.5)

#viruses

print("Sending antivirus script to every local IP on " + ip)
time.sleep(4)
print("Script prepared, disabling antivirus and protection...")
time.sleep(1)
print("Disabled, injecting malware...")
time.sleep(1)
print("Sending and executing MEMZ virus")
time.sleep(1)
print("Sending and executing NoEscape.exe")
time.sleep(1)
print("Encrypting C:/users/ directory...")
print("Encrypting entire D:/ directory if existing...")
time.sleep(1)
print("Connecting to router portal...")
time.sleep(2)
print(Fore.GREEN + "Connected")
print(Fore.WHITE + "Logging in")
print("Pass: admin\nUser: admin")
time.sleep(1)
print("Changed password and username...")
time.sleep(1)

#enf

time.sleep(2)
print("Deleting IP connection log from router and local ISP...")
time.sleep(4)
print(Fore.GREEN + "Succesfully deleted")
time.sleep(2)
print("\n")
print(Fore.RED + "Closing script")
print(Fore.WHITE + "\nAlso this is fake hack")

input("Hit ENTER to exit")